# Generated by Django 4.1.7 on 2023-03-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nome Cadastrado:')),
                ('sobrenome', models.CharField(blank=True, max_length=150, null=True, verbose_name='Sobre Nome:')),
                ('sexo', models.CharField(choices=[('F', 'F'), ('M', 'M')], default='M', max_length=1)),
                ('altura', models.CharField(max_length=20, null=True)),
                ('peso', models.CharField(max_length=20, null=True)),
                ('nascimento', models.DateField()),
                ('numero', models.CharField(max_length=30, null=True, verbose_name='numero')),
                ('foto', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
